export const missions = {
  missions: {
    dailyMissions: {
      title: "Daily Missions",
      items: [
        {
          missionId: "001",
          icon: "🎥",
          name: "Watch Your First Video",
          description:
            "Explore the GinUp video feed and watch your first impact video!",
          reward: 20,
          progress: "Not Started",
          deadline: "Today at 11:59 PM",
          status: "active",
        },
        {
          missionId: "002",
          icon: "🤝",
          name: "Add 3 New Friends",
          description: "Connect with 3 new members in the GinUp community.",
          reward: 15,
          steps: 3,
          currentStep: 1,
          progress: "In Progress",
          deadline: "Today at 11:59 PM",
          status: "active",
        },
        {
          missionId: "003",
          icon: "🔍",
          name: "Explore the Impact Hub",
          description:
            "Browse through GinUp and discover ongoing projects and initiatives.",
          reward: 10,
          progress: "In Progress",
          deadline: "Today at 11:59 PM",
          status: "active",
        },
        {
          missionId: "004",
          icon: "📢",
          name: "Share an Initiative Update",
          description:
            "Post your thoughts or update about a project to inspire others.",
          reward: 25,
          progress: "Not Started",
          deadline: "Today at 11:59 PM",
          status: "active",
        },
        {
          missionId: "005",
          icon: "💬",
          name: "Chat with the AI Assistant",
          description:
            "Ask a question or get help from the AI assistant in GinUp.",
          reward: 5,
          progress: "Completed",
          deadline: "Today at 11:59 PM",
          status: "completed",
        },
      ],
    },
    weeklyMissions: {
      title: "Weekly Missions",
      items: [
        {
          missionId: "006",
          icon: "🎉",
          name: "Participate in 3 Impact Events",
          description:
            "Engage in at least 3 community events or webinars this week.",
          reward: 50,
          steps: 3,
          currentStep: 2,
          progress: "In Progress",
          deadline: "This Week",
          status: "active",
        },
        {
          missionId: "007",
          icon: "✍️",
          name: "Create 2 Impact Initiatives",
          description: "Share 2 new initiative ideas or projects on GinUp.",
          reward: 40,
          steps: 2,
          currentStep: 0,
          progress: "Not Started",
          deadline: "This Week",
          status: "active",
        },
        {
          missionId: "008",
          icon: "😄",
          name: "Earn 100 Ginx",
          description:
            "Complete missions or engage with content to earn at least 100 Ginx this week.",
          reward: 75,
          progress: "In Progress",
          deadline: "This Week",
          status: "active",
        },
        {
          missionId: "009",
          icon: "🏆",
          name: "Redeem a Reward in GinUp Rewards",
          description: "Use your Ginx to redeem a special reward.",
          reward: 30,
          progress: "Not Started",
          deadline: "This Week",
          status: "active",
        },
        {
          missionId: "010",
          icon: "🤝",
          name: "Make 5 New Friends",
          description: "Connect with at least 5 new members on GinUp.",
          reward: 50,
          steps: 5,
          currentStep: 3,
          progress: "In Progress",
          deadline: "This Week",
          status: "active",
        },
      ],
    },
  },
};
